algoritmo "Operador Relacionais"
var

    A, B, C: inteiro

inicio
    A <- 2
    B <- 3
    C <- 5

    escreval(A<B)       //Verdadeiro
    escreval(A=B)       //Falso
    escreval(A<>B)      //Verdadeiro
    escreval(A>2)       //Falso
    escreval(A>=2)      //Verdadeiro
    escreval(C=A+B)     //Verdadeiro
    escreval(C>=B^A)    //Falso
    escreval(C<=B^A)    //Verdadeiro
    escreval(B<=C%2)    //Falso
    escreval(1<=C%2)    //Verdadeiro

fimalgoritmo